### PR TITLE
Modernize pom.xml plugins

### PR DESCRIPTION
**Pull request by grimreaper**

### CODE REVIEW

**Comment by jstuyts** [comment]
If you can remove all `version` tags from the child POMs, that would be great. There are still duplicate versions for the same plug-in now. Thanks in advance.

**Comment by grimreaper** [comment]
done

**Comment by jstuyts** [comment]
Almost there. The versions for `maven-project-info-reports-plugin` have been removed, but there is no plug-in entry specifying the version in the plug-in management section of the root POM.

**Comment by grimreaper** [comment]
In this case it wouldn't have mattered since it got its version from the super-pom, but set explicitly anyways.

**Comment by jstuyts** [comment]
Thank you.

One more thing: I don't understand which super-POM you mean. Can you tell me which POM would provide the version for the project info reports plug-in if it is not specified by plug-in management in the root POM? TIA

**Comment by grimreaper** [comment]
The POM supplied by maven itself. While I'm not quite as familiar with maven as I am with Gradle, https://maven.apache.org/ref/3.5.0/maven-model-builder/super-pom.html seems to be the starting point for this.

**Comment by grimreaper** [comment]
Another thing: I may also be mis-understanding what is happening here, and the version isn't being set by the super-pom but is being set implicitly to the latest available version. either way the version didn't change when setting it explicitly (and I have mixed feelings on version pinning on its own)

**Comment by jstuyts** [comment]
I see. I prefer explicit versioning to prevent version updates from breaking the build. Version updates need to be tested locally first, so you can fix any problems immediately.

But I agree that we need to be proactive about using the latest versions of plug-ins.

**Pull request merged**
