### PR TITLE
Use latest maven compiler plugin; allow Java 8

### PR DESCRIPTION
**Pull request by grimreaper**
This allows us to use Java 8 source code in this project.

### CODE REVIEW

**Comment by jstuyts** [comment]
You forgot to remove existing `source` tags in modules `main`, `extensions/hadoop` and `extensions/java7`. Remove those and I will merge.

**Comment by grimreaper** [comment]
hrm, didn't realize that you can't target bytecode older than than the source. Makes sense when I think about it. This now proposes targeting 1.8 in full (and requiring 1.8 JVM).
Its old enough that most projects would be okay with it (hopefully)

**Comment by jstuyts** [comment]
It is possible to use an older target with a newer source, but not the other way around.

There are still people using argparse4j on JDK 6, so we cannot upgrade to JDK 8: https://github.com/tatsuhiro-t/argparse4j/issues/63

We want to be able to set the target JDK per module (1.6 for the core, 1.7 for the Java 7 extension, etc.), but it is fine to set the sources JDK to 1.8 for all modules. Building with 1.8 is also not a problem, and I have a change in the queue that will check that classes from newer JDKs are not used on the CI server: https://github.com/tatsuhiro-t/argparse4j/issues/95

**Comment by jstuyts** [comment]
Because of https://github.com/tatsuhiro-t/argparse4j/issues/95 (which I assume will be merged soon) there is no need to specify the JDK in the Travis file.

**Comment by jstuyts** [comment]
I am sorry to see that you decided to revert your changes. The switch to Java 1.8 syntax is not a problem at all, but we must continue to support users that still deploy on Java 1.6. You can create another PR that only changes the source version to 1.8, or else I will make the changes myself soonish.

**Comment by grimreaper** [comment]
I plan on making the changes, this PR conflicted in ways that were difficult to recover. 
That said, if you get to it first, it will still be cool.

**Pull request closed without merging**
