### PR TITLE
Switched from global variables to a builder

### PR DESCRIPTION
**Pull request by jstuyts**
I deprecated all the old methods that use global variables.

### CODE REVIEW

**Comment by jstuyts** [comment]
I forgot to update the documentation. I am working on that now, and I expect to have it ready this week.

**Comment by tatsuhiro-t** [comment]
Thank you.  The code looks good to me.  Will merge after documentation is updated, and reviewed.

**Comment by jstuyts** [comment]
The documentation has been updated. Please consider the following during your review:

* I took the liberty to use 0.8.0 as the version number for the release that will contain these changes. Please change it to the one you would like to use. See `usage.rst` and `migration.rst`.
* There are some changes to Clojure code that I did not test. Please review the modifications in `examples.rst`.
* The documentation for `cjkWidthHack(...)` does not have code showing the effect of the setting. I tried to use the Japanese text in `examples.rst`, but it looks like these characters are all the same width.  It would be great if you could extend the code example to show that wide characters are counted as 2 columns.

**Comment by tatsuhiro-t** [comment]
I agree that the next version is 0.8.0.
I tested with examples.rst, and it works for me.  Perhaps, it requires Japanese locale to work.

**Comment by tatsuhiro-t** [comment]
Clojure example also works for me.  Thank you!

This PR looks good to me.  Are you ready to merge?

**Comment by jstuyts** [comment]
Yes, I am ready for merging. I have no changes anymore for this issue.

**Comment by tatsuhiro-t** [comment]
Thank you.  Merged now.

**Comment by jstuyts** [comment]
Great. Thank you.

**Pull request merged**
